---
name: cmpsc-203-spring-2019-lab2
break: true
indent: 4
---
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
report.md:
    mdl
    proselint
conduct.md:
    mdl
    proselint
assessment.md:
    mdl
    proselint
# --> check the number of commits beyond a threshold
--commits 11
